Update myenv

diff --git a/myenv b/myenv
--- a/myenv
+++ b/myenv
@@ -12,6 +12,17 @@ VERSION=1.0.0
 # ##############################################################################
 if [[ -z "${BASH_VERSION:-}" ]]; then echo "Error: Bash is required." >&2; exit 1; fi
 
+
+#-------------------------------------------------------------------------------
+debug() { [[ "${DEBUG}" == "true" ]] && echo >&2 -e "${VERBOSE}$*${NOFORMAT}"; }
+info() { echo >&2 -e "${INFO}$*${NOFORMAT}"; }
+error() { echo >&2 -e "${ERROR}$*${NOFORMAT}"; }
+prompt_yn() { read -r -p "${1} " opt; [[ "${opt:-"y"}" == "y" ]] || [[ "${opt}" == "Y" ]]; }
+prompt_ny() { read -r -p "${1} " opt; [[ "${opt:-"n"}" != "y" ]] && [[ "${opt}" != "Y" ]]; }
+usage() { sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0" | sed 's/{SCRIPT_NAME}/'"${ENV_NAME}"'/g'; exit 1; }
+cleanup() { cd "${OLD_PWD:-"${PWD}"}" >/dev/null || true; }
+#-------------------------------------------------------------------------------
+
 set -uo pipefail
 trap cleanup SIGINT SIGTERM ERR EXIT
 OLD_PWD="$(pwd || true)"
@@ -25,21 +36,14 @@ REPO_BRANCH="${REPO_BRANCH:-"${BRANCH:-"master"}"}"
 BIN_DIR="${HOME}/.local/bin"
 DEBUG=${DEBUG:-"false"}
 export PATH="${ENV_HOME}:${PATH}"
+if [[ -z "${USER}" ]]; then
+    export USER="$(basename "${HOME}")"
+fi
 
 # Settings for collor output
 if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
     NOFORMAT='\033[0m' INFO='\033[0;32m' VERBOSE='\033[0;36m' ERROR='\033[0;31m';
 else NOFORMAT='' INFO='' VERBOSE='' ERROR=''; fi
-
-#-------------------------------------------------------------------------------
-debug() { [[ "${DEBUG}" == "true" ]] && echo >&2 -e "${VERBOSE}$*${NOFORMAT}"; }
-info() { echo >&2 -e "${INFO}$*${NOFORMAT}"; }
-error() { echo >&2 -e "${ERROR}$*${NOFORMAT}"; }
-prompt_yn() { read -r -p "${1} " opt; [[ "${opt:-"y"}" == "y" ]] || [[ "${opt}" == "Y" ]]; }
-prompt_ny() { read -r -p "${1} " opt; [[ "${opt:-"n"}" != "y" ]] && [[ "${opt}" != "Y" ]]; }
-usage() { sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0" | sed 's/{SCRIPT_NAME}/'"${ENV_NAME}"'/g'; exit 1; }
-
-cleanup() { cd "${OLD_PWD:-"${PWD}"}" >/dev/null || true; }
 
 #-------------------------------------------------------------------------------
 remove_symlinks_from_bin() {
