Save

diff --git a/home/.local/bin_macos/gqview b/home/.local/bin_macos/gqview
--- a/home/.local/bin_macos/gqview
+++ b/home/.local/bin_macos/gqview
@@ -1,1 +1,10 @@
-/usr/bin/open
+#!/bin/sh
+
+if [ ! -e "/Applications/qView.app/" ]; then
+    echo "Error: qView.app not found. Please install qView.app first"
+    echo "# brew install gqview"
+    echo "https://interversehq.com/qview/"
+    exit 1
+fi
+
+open -a qView.app "${1:-"${PWD}"}"
