Add WSL specific wsl settings

diff --git a/macos/home/.config/bashrc_macos b/macos/home/.config/bashrc_macos
--- a/macos/home/.config/bashrc_macos
+++ b/macos/home/.config/bashrc_macos
@@ -1,3 +1,57 @@
-# To disable 'The default interactive shell is now zsh' message
+###############################################################################
+# Custom user bashrc file settings for MacOS system.
+####################################i###########################################
+if [ -n "$SSH_TTY" ]; then export TERM=xterm; fi # fix "screen" on OSX
+if [ -f /etc/bash_completion ]; then  . /etc/bash_completion; fi
+if [ -d "${USERBIN}" ]; then
+    # Hide ../bin directory from Finder by default 
+    chflags hidden "${USERBIN}"
+fi
+
+toclip() {
+    #remove last 'newline' char and copy to clipboard
+    awk '{q=p;p=$0}NR>1{print q}END{ORS = ""; print p}'| pbcopy
+}
+
+fromclip() {
+    pbpaste
+}
+
+
+iterm_title () {
+    TITLE=${1:-"$(basename "${PWD}")"}
+    export PROMPT_COMMAND='echo -ne "\033]0;$TITLE\007"'
+}
+
+open_app() {
+    [ -z "${1}" ] && echo "Error: usage open_app <app_name> [arg1]" && exit 1
+    if [ -z "${2}" ]; then
+        /usr/bin/open -a "${1}" "${2}"
+    else
+        /usr/bin/open -a "${1}"
+    fi
+}
+
+alias lt='ls -ATlh'
+alias ports='lsof -i -n -P'
+alias osinfo='sw_vers'
+alias osver='sw_vers -productVersion'
+alias srm='rm -rvP'
+alias sdelete='rm -rvP'
+alias brew-cleanup='brew cleanup; rm -f -r /Library/Caches/Homebrew/*'
+alias xopen='/usr/bin/open'
+alias ncdu-root='sudo ncdu / --exclude /Volumes --exclude /System/Volumes --exclude /dev --exclude /private'
+alias qview='open -a qview.app'
+alias filerestore='testdisk'
+
+# supress zsh verbose message in macOS Catalina
 export BASH_SILENCE_DEPRECATION_WARNING=1
 
+export PATH="$(ls -d ${HOME}/Library/Python/3.*/bin | tail -n 1):$(ls -d ${HOME}/Library/Python/2.*/bin | tail -n 1):$PATH:/usr/local/sbin"
+export JAVA_HOME=$(/usr/libexec/java_home)
+export NODE_PATH=/usr/local/lib/node_modules
+
+# Fix the DISPLAY variable if it is empty
+if [ -z "$SSH_TTY" ] && [ -z "$DISPLAY" ]; then
+    export DISPLAY=":0"
+fi
